version: '1'

services:


    ms-express:
        image: msexpress
        build: 
            context: ./ex
            dockerfile: Dockerfile
        container_name: ms-express
        ports: 
            - "7000:3000"
        restart: "no"


    ms-php:
        image: msphp
        build: 
            context: ./ph
            dockerfile: Dockerfile
        container_name: ms-php
        ports: 
            - "8081:80"
        restart: "no"
    
    ms-python:
        image: mspython
        build: 
            context: ./py
            dockerfile: Dockerfile
        container_name: ms-python
        ports: 
            - "5000:4000"
        restart: "no"

    ms-react:
        image: msreact
        build: 
            context: ./py
            dockerfile: Dockerfile
        container_name: ms-react
        ports: 
            - "3001:3000"
        environment: 
            - MS_EXPRESS_HOST=ms-express
            - MS_EXPRESS_PORT=3000
            - MS_PHP_HOST=ms-php
            - MS_PHP_PORT=80
            - MS_PYTHON_HOST=ms-python
            - MS_PYTHON_PORT=4000
        restart: "no"

      

